# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kldvFMnGADw55LuyVx3yStvuoye7LuFs
"""

import streamlit as st
import os
os.system('pip install nltk')
import nltk
nltk.download('punkt_tab')
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import pandas as pd
from collections import Counter
import string
from deep_translator import GoogleTranslator


# Streamlit UI elements
st.title("Text Analysis and Translation App")

st.write("Paste your text data below (each line will be treated as a separate entry):")
input_text = st.text_area("Enter text here", height=200)

if st.button("Process Text"):
    if input_text:
        titles = [line.strip() for line in input_text.splitlines() if line.strip()]

        # Your processing logic (modified for Streamlit)
        word_counter = Counter()
        stop_words = set(stopwords.words('english'))
        punctuation = set(string.punctuation)

        for title in titles:
            words = word_tokenize(title)
            words = [word.lower() for word in words if word.lower() not in stop_words and word not in punctuation]
            word_counter.update(words)

        top_1000_words = word_counter.most_common(1000)

        translator = GoogleTranslator(source='auto', target='en')
        translations = []
        for i, (word, freq) in enumerate(top_1000_words):
            translated_word = translator.translate(word)
            translations.append((word, translated_word, freq))

        top_1000_df = pd.DataFrame(translations, columns=['Word', 'Translation', 'Frequency'])

        # Display the DataFrame in Streamlit
        st.write("## Results:")
        st.dataframe(top_1000_df)

        # Download link for the CSV
        csv = top_1000_df.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="Download data as CSV",
            data=csv,
            file_name='translated_words.csv',
            mime='text/csv',
        )
    else:
        st.warning("Please enter some text.")
